ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS confirmed_at timestamp with time zone;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS processing_at timestamp with time zone;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS out_for_delivery_at timestamp with time zone;

CREATE TABLE IF NOT EXISTS public.price_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id integer,
  old_price numeric,
  new_price numeric,
  changed_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.price_history ENABLE ROW LEVEL SECURITY;
CREATE POLICY price_history_select_admin ON public.price_history FOR SELECT TO authenticated USING (public.is_admin());
CREATE POLICY price_history_insert_admin ON public.price_history FOR INSERT TO authenticated WITH CHECK (public.is_admin());
