ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS gstin text DEFAULT '';

ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS gstin text DEFAULT '';

ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS customer_email text DEFAULT '';

CREATE TABLE IF NOT EXISTS public.sales_summary (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_date date NOT NULL DEFAULT CURRENT_DATE,
  total_orders bigint DEFAULT 0,
  total_revenue numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.sales_summary ENABLE ROW LEVEL SECURITY;

CREATE POLICY sales_summary_select_admin
ON public.sales_summary
FOR SELECT
TO authenticated
USING (public.is_admin());
